frontend/models/Loads.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "loads".
 *
 * @property int $id ID
 * @property int $user_id User ID
 * @property int $industry_id Industry ID
 * @property string $scheduling_type Scheduling Type
 * @property string|null $source_city Source City
 * @property string|null $destination_city Destination City
 * @property string|null $material_type Material Type
 * @property string|null $weight Weight
 * @property string|null $truck_type Truck Type
 * @property int|null $no_of_trucks No. of Trucks
 * @property string|null $reporting_date Selected Date
 * @property string|null $reporting_time Reporting Time
 * @property string|null $description Description
 * @property string|null $current_status Current Status
 * @property string $status Status
 * @property string|null $created_at Created On
 * @property string|null $updated_at Updated On
 * @property int|null $created_by Created By
 * @property int|null $updated_by Updated By
 *
 * @property User $user
 * @property Industry $industry
 */
class Loads extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'loads';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'industry_id'], 'required'],
            [['user_id', 'industry_id', 'no_of_trucks', 'created_by', 'updated_by'], 'integer'],
            [['scheduling_type', 'status'], 'string'],
            [['reporting_date', 'created_at', 'updated_at'], 'safe'],
            [['source_city', 'destination_city', 'material_type', 'truck_type', 'description'], 'string', 'max' => 250],
            [['weight'], 'string', 'max' => 50],
            [['reporting_time', 'current_status'], 'string', 'max' => 20],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['industry_id'], 'exist', 'skipOnError' => true, 'targetClass' => Industry::className(), 'targetAttribute' => ['industry_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'industry_id' => Yii::t('app', 'Industry ID'),
            'scheduling_type' => Yii::t('app', 'Scheduling Type'),
            'source_city' => Yii::t('app', 'Source City'),
            'destination_city' => Yii::t('app', 'Destination City'),
            'material_type' => Yii::t('app', 'Material Type'),
            'weight' => Yii::t('app', 'Weight'),
            'truck_type' => Yii::t('app', 'Truck Type'),
            'no_of_trucks' => Yii::t('app', 'No. of Trucks'),
            'reporting_date' => Yii::t('app', 'Selected Date'),
            'reporting_time' => Yii::t('app', 'Reporting Time'),
            'description' => Yii::t('app', 'Description'),
            'current_status' => Yii::t('app', 'Current Status'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created On'),
            'updated_at' => Yii::t('app', 'Updated On'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery|UserQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[Industry]].
     *
     * @return \yii\db\ActiveQuery|IndustryQuery
     */
    public function getIndustry()
    {
        return $this->hasOne(Industry::className(), ['id' => 'industry_id']);
    }

    /**
     * {@inheritdoc}
     * @return LoadsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new LoadsQuery(get_called_class());
    }
}

backend/controllers/LoadsController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Loads;
use app\models\LoadsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LoadsController implements the CRUD actions for Loads model.
 */
class LoadsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	public function actionImport()
    {
        $model = new Loads();
        if(isset($_FILES['uploadExcel']) && isset($_POST['Loads'])) {
            $post = $_POST['Loads']; 
            $fileName = $_FILES["uploadExcel"]["name"];
            $ext = pathinfo($fileName, PATHINFO_EXTENSION);
            $fileName = time().'.'.$ext;
            // $file = UploadedFile::getInstances($model, 'uploadExcel');
            // $expload = explode(".", $file->name);
            // $ext = end($expload);
            // $excel = time() . ".{$ext}";
            // $path = UPLOAD_DIR_PATH . 'mandi/' . $excel;
            // $upload_file = $file->saveAs($path,false);
            $path = UPLOAD_DIR_PATH . '/' .$fileName;
            if(move_uploaded_file($_FILES["uploadExcel"]["tmp_name"], $path)) {
                $inputFile = '../uploads/'.$fileName;
           
                try{
                    $inputFileType = \PHPExcel_IOFactory::identify($inputFile);
                    $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
                    $objPHPExcel = $objReader->load($inputFile);
                } catch (Exception $e) {
                    die('Error');
                }
                //$objPHPExcel1 = \PHPExcel_IOFactory::load($inputFile);
                //$sheetData = $objPHPExcel->getActiveSheet()->toArray(null, true, true, true);
                //print_r($sheetData);exit;
                $sheet = $objPHPExcel->getSheet(0);
                $highestRow = $sheet->getHighestRow();
                $highestColumn = $sheet->getHighestColumn();
           
                for($row=1; $row <= $highestRow; $row++)  {

                    $rowData = $sheet->rangeToArray('A'.$row.':'.$highestColumn.$row,NULL,TRUE,TRUE);
                    if($row==1)
                    {
                        continue;
                    }
                    if($rowData[0][0]=='')
                    {
                        continue;
                    }
					
					$i=0;
					//$model = Loads::find()->where(['mobile_number' => trim($rowData[0][0])])->one();
					//if(empty($model)) {
						//continue;
					//}
					$model = new Loads();
					$ind = Industry::find()->where(['mobile_number' => trim($rowData[0][0])])->one();
					//print_r($rowData[0]);exit;
					if(!empty(trim($rowData[0][$i])))
					$model->mobile_number  = trim($rowData[0][$i]);
					$model->industry_id	  = $ind->id;
					$model->industry_user_id  = $ind->user_id;
					$model->full_name  = $ind->first_name.' '.$ind->last_name;
					$model->company_name  = $ind->company_name;
				
					$i=1;
					if(!empty(trim($rowData[0][++$i])))
                    $model->source_address_line1 = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->source_address_line2 = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->source_pincode = trim($rowData[0][$i]); 
				
					//if(!empty(trim($rowData[0][++$i])))
                    //$model->source_state  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
                    $model->source_district = trim($rowData[0][$i]);
				
					//if(!empty(trim($rowData[0][++$i])))
                    $model->source_city  = $model->source_district;
				
					if(!empty(trim($rowData[0][++$i])))
					$model->source_area  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->source_landmark  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->destination_address_line1  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->destination_address_line2  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->destination_pincode  = trim($rowData[0][$i]);
				
					//if(!empty(trim($rowData[0][++$i])))
					//$model->destination_state  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->destination_district  = trim($rowData[0][$i]);
				
					//if(!empty(trim($rowData[0][++$i])))
					$model->destination_city  = $model->destination_district;
				
					if(!empty(trim($rowData[0][++$i])))
					$model->destination_area  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->destination_landmark  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->load_type  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->scheduling_type  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->material_type  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->weight  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->truck_type  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->no_of_trucks  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->reporting_date  = date('Y-m-d',strtotime(trim($rowData[0][$i])));
				
					if(!empty(trim($rowData[0][++$i])))
					$model->reporting_time  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->bid_closing_date  = date('Y-m-d',strtotime(trim($rowData[0][$i])));
				
					if(!empty(trim($rowData[0][++$i])))
					$model->bid_closing_time  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->quotation_amount_type  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->estimated_quotation_amount  = trim($rowData[0][$i]);
				
					if(!empty(trim($rowData[0][++$i])))
					$model->total_amount  = trim($rowData[0][$i]);
					else
					$model->total_amount  = $model->estimated_quotation_amount;
				
					if(!empty(trim($rowData[0][++$i])))
					$model->description  = trim($rowData[0][$i]);
				
					$model->created_by  = Yii::$app->user->id;
                    if($model->save(false)) {
						$id = $model->id;
						$model = Loads::findOne($id);
						$model->booking_id = 'LD'.$id;
						$model->save(false);
					}
                }
                unlink($path);
                return $this->redirect(['index']);
            }
        }
        return $this->render('import', [
            'model' => $model,
        ]);
    }
    /**
     * Lists all Loads models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoadsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Loads model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

	public function actionDetail($id)
    {
        $quotModel = new \app\models\QuotationSearch();
        $dataProviderQuot = $quotModel->search(Yii::$app->request->queryParams);
		$dataProviderQuot->query->andWhere(['load_id' => $id]);
		
		$truckModel = new \app\models\QuotationTruckSearch();
        $dataProviderTruck = $truckModel->search(Yii::$app->request->queryParams);
		$dataProviderTruck->query->andWhere(['load_id' => $id])->andWhere('assigned_driver_user_id >0');
		
        return $this->render('detail', [
            'model' => $this->findModel($id),
			'quotModel' => $quotModel,
            'dataProviderQuot' => $dataProviderQuot,
			'truckModel' => $truckModel,
            'dataProviderTruck' => $dataProviderTruck,
        ]);
    }
	public function actionTracking()
    {
        return $this->render('tracking');
    }
    /**
     * Creates a new Loads model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Loads();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Loads model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Loads model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Loads model based on its primary key value.

backend/views/loads/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Loads */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loads-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'ref_rejected_load_id')->textInput() ?>

    <?= $form->field($model, 'booking_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'industry_user_id')->textInput() ?>

    <?= $form->field($model, 'industry_id')->textInput() ?>

    <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'load_address_type')->dropDownList([ 'Intrastate' => 'Intrastate', 'Interstate' => 'Interstate', 'Neighboring City' => 'Neighboring City', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'company_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_address_id')->textInput() ?>

    <?= $form->field($model, 'source_address_line1')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_address_line2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_pincode')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_state')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_district')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_city')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_area')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'source_landmark')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_address_line1')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_address_line2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_pincode')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_state')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_district')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_city')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_area')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'destination_landmark')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'load_type')->dropDownList([ 'Full Load' => 'Full Load', 'Part Load' => 'Part Load', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'scheduling_type')->dropDownList([ 'One Time' => 'One Time', 'Daily' => 'Daily', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'material_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'weight')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'truck_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_of_trucks')->textInput() ?>

    <?= $form->field($model, 'bid_closing_date')->textInput() ?>

    <?= $form->field($model, 'bid_closing_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'reporting_date')->textInput() ?>

    <?= $form->field($model, 'reporting_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'max_bid_amount')->textInput() ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'share_to_preferred')->dropDownList([ 'Yes' => 'Yes', 'No' => 'No', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'assigned_status')->dropDownList([ 'Open' => 'Open', 'Assigned' => 'Assigned', 'Cancelled' => 'Cancelled', 'Rejected' => 'Rejected', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'assigned_at')->textInput() ?>

    <?= $form->field($model, 'assigned_user_id')->textInput() ?>

    <?= $form->field($model, 'assigned_full_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'assigned_mobile_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'assigned_company_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'assigned_bid_amount')->textInput() ?>

    <?= $form->field($model, 'assigned_truck_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'part_load_quotation_date')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'reject_reason')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'rejected_from')->dropDownList([ '' => '', 'Industry' => 'Industry', 'Transporter' => 'Transporter', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'rejected_by')->textInput() ?>

    <?= $form->field($model, 'rejected_at')->textInput() ?>

    <?= $form->field($model, 'status')->dropDownList([ 'Active' => 'Active', 'Inactive' => 'Inactive', 'Deleted' => 'Deleted', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'updated_by')->textInput() ?>

    <?= $form->field($model, 'quotations')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/loads/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Loads */

$this->title = Yii::t('app', 'Create Loads');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Loads'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loads-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/loads/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\LoadsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Loads');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loads-index">
	<!--Success/Error Message --->
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="row col-xs-12 col-sm-12 col-md-12 col-xl-12 alert alert-success alert-dismissable" style="width: 100%; margin-left: 0px;">
        <div class="col-md-12">
         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <?= Yii::$app->session->getFlash('success') ?>
        </div>
        </div>
    <?php endif; ?>
	<?php if (Yii::$app->session->hasFlash('error')): ?>
		<div class="row col-xs-12 col-sm-12 col-md-12 col-xl-12 alert alert-error alert-dismissable" style="width: 100%; margin-left: 0px;">
		<div class="col-md-12">
		 <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
			 <!--<h4><i class="icon fa fa-check"></i>Saved!</h4>-->
			 <?= Yii::$app->session->getFlash('error') ?>
		</div>
		</div>
   <?php endif; ?>
    <!--Success/Error Message --->
	
	<?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'ref_rejected_load_id',
            'booking_id',
            //'industry_user_id',
            //'industry_id',
			'company_name',
            'full_name',
            'mobile_number',
            //'load_address_type',
            //'source_address_id',
            //'source_address_line1',
            //'source_address_line2',
            //'source_pincode',
            //'source_state',
            //'source_district',
            'source_city',
            //'source_area',
            //'source_landmark',
            //'destination_address_line1',
            //'destination_address_line2',
            //'destination_pincode',
            //'destination_state',
            //'destination_district',
            'destination_city',
            //'destination_area',
            //'destination_landmark',
            //'load_type',
            //'scheduling_type',
            'material_type',
            //'weight',
            'truck_type',
            //'no_of_trucks',
            //'bid_closing_date',
            //'bid_closing_time',
            'reporting_date',
            //'reporting_time',
            //'max_bid_amount',
            //'description',
            //'share_to_preferred',
            'assigned_status',
            //'assigned_at',
            //'assigned_user_id',
            //'assigned_full_name',
            //'assigned_mobile_number',
            //'assigned_company_name',
            //'assigned_bid_amount',
            //'assigned_truck_id',
            //'part_load_quotation_date',
            //'reject_reason',
            //'rejected_from',
            //'rejected_by',
            //'rejected_at',
            //'status',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',
            //'quotations',

            [
                'header' => 'Action',
                'headerOptions' => ['width' => '4%','class' => ' table-th'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{detail}',
                'buttons' =>
                [
                    'detail' => function($url, $model) {
                         $url = Yii::$app->urlManager->createUrl(['/loads/detail']).'&id=' . $model->id;
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'title' => Yii::t('app', 'Details'),
                                    'data-pjax' => '0',
                        ]);
                    },
					
                ],
                'visible' => TRUE
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/loads/quotation.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\QuotationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//$this->title = Yii::t('app', 'Quotations');
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="quotation-index">
	<?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'load_id',
            //'user_id',
            'full_name',
            'mobile_number',
            'company_name',
            'bid_amount',
            //'part_load_quotation_date',
            //'truck_id',
            //'remark',
            //'assigned_to_me',
            //'status',
            [
				'label' => 'Created At',
				'attribute' => 'created_at',
				'format' => ['date', 'php:d-m-Y'],
				'headerOptions' => ['style' => 'width:8%'],
				//'filter' => false,
            ],
            //'updated_at',
            //'created_by',
            //'updated_by',

            //['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/loads/quotation_truck.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\QuotationTruckSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//$this->title = Yii::t('app', 'Quotation Trucks');
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="quotation-truck-index">
    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'quotation_id',
            //'load_id',
            //'truck_id',
            //'user_id',
            'vehicle_no',
            //'gps_installed',
            'weight',
            'truck_type',
            //'rc_no',
            //'rc_photo',
            'license_no',
            //'license_photo',
            //'permit_type',
            //'permit_photo',
            //'insurance_policy_no',
            //'insurance_policy_photo',
            //'pollution_no',
            //'pollution_photo',
            //'rto_fitness_certificate_no',
            //'rto_fitness_certificate_photo',
            //'local_registration_no',
            //'local_registration_photo',
            //'registration_address',
            //'registration_mobile',
            //'office_landline_no',
            //'email:email',
            //'gross_weight',
            //'verified',
            //'assigned_driver_id',
            'assigned_driver_name',
            'assigned_driver_mobile',
            //'assigned_driver_aadhaar_number',
            //'assigned_driver_at',
			'eWay_bill_no',
			'trip_status',
            //'status',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',

            [
                'header' => 'Action',
                'headerOptions' => ['width' => '4%','class' => ' table-th'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{tracking}',
                'buttons' =>
                [
                    'tracking' => function($url, $model) {
                         $url = Yii::$app->urlManager->createUrl(['/loads/tracking']).'&lid='.$model->load_id.'&tid='.$model->truck_id.'&id='.$model->id;
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'title' => Yii::t('app', 'Tracking'),
                                    'data-pjax' => '0',
									'target' => '_blank'
                        ]);
                    },
					
                ],
                'visible' => TRUE
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>