user(unused)/models/Industry.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "industry".
 *
 * @property int $id ID
 * @property int $user_id User ID
 * @property string $first_name First Name
 * @property string $last_name Last Name
 * @property string $email Email
 * @property string $mobile_number Mobile No.
 * @property string $company_name Company Name
 * @property int $company_type_id Company Type ID
 * @property string $company_type Company Type
 * @property string $incorporation_certificate_number Incorporation Certificate Number
 * @property string $shop_establishment_certificate_number Shop Establishment Certificate Number
 * @property string $pan_number PAN No.
 * @property string $incorporation_certificate_photo Incorporation Certificate Photo
 * @property string $shop_establishment_certificate_photo Shop Establishment Certificate Photo
 * @property string $gst_number GST No.
 * @property string $aadhaar_number Aadhaar No.
 * @property string $aadhaar_photo Aadhaar Photo
 * @property string $pan_photo PAN Photo
 * @property string $address_line1 Address line1
 * @property string $address_line2 Address line2
 * @property string $pincode Pincode
 * @property string $country Country
 * @property string $state State
 * @property string $district District
 * @property string $city City
 * @property string $area Area
 * @property string $landmark
 * @property string $remark Remark
 * @property int $verified Department Verification
 * @property string $status Status
 * @property string $created_at Created On
 * @property string $updated_at Updated On
 * @property int $created_by Created By
 * @property int $updated_by Updated By
 *
 * @property User $user
 */
class Industry extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'industry';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id', 'company_type_id', 'verified', 'created_by', 'updated_by'], 'integer'],
            [['status'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['first_name', 'last_name', 'email', 'company_name', 'company_type', 'incorporation_certificate_photo', 'shop_establishment_certificate_photo', 'aadhaar_photo', 'pan_photo', 'address_line1', 'address_line2', 'area', 'landmark', 'remark'], 'string', 'max' => 250],
            [['mobile_number', 'pincode'], 'string', 'max' => 10],
            [['incorporation_certificate_number', 'shop_establishment_certificate_number', 'state', 'district', 'city'], 'string', 'max' => 100],
            [['pan_number', 'gst_number', 'aadhaar_number', 'country'], 'string', 'max' => 50],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'email' => Yii::t('app', 'Email'),
            'mobile_number' => Yii::t('app', 'Mobile No.'),
            'company_name' => Yii::t('app', 'Company Name'),
            'company_type_id' => Yii::t('app', 'Company Type ID'),
            'company_type' => Yii::t('app', 'Company Type'),
            'incorporation_certificate_number' => Yii::t('app', 'Incorporation Certificate Number'),
            'shop_establishment_certificate_number' => Yii::t('app', 'Shop Establishment Certificate Number'),
            'pan_number' => Yii::t('app', 'PAN No.'),
            'incorporation_certificate_photo' => Yii::t('app', 'Incorporation Certificate Photo'),
            'shop_establishment_certificate_photo' => Yii::t('app', 'Shop Establishment Certificate Photo'),
            'gst_number' => Yii::t('app', 'GST No.'),
            'aadhaar_number' => Yii::t('app', 'Aadhaar No.'),
            'aadhaar_photo' => Yii::t('app', 'Aadhaar Photo'),
            'pan_photo' => Yii::t('app', 'PAN Photo'),
            'address_line1' => Yii::t('app', 'Address line1'),
            'address_line2' => Yii::t('app', 'Address line2'),
            'pincode' => Yii::t('app', 'Pincode'),
            'country' => Yii::t('app', 'Country'),
            'state' => Yii::t('app', 'State'),
            'district' => Yii::t('app', 'District'),
            'city' => Yii::t('app', 'City'),
            'area' => Yii::t('app', 'Area'),
            'landmark' => Yii::t('app', 'Landmark'),
            'remark' => Yii::t('app', 'Remark'),
            'verified' => Yii::t('app', 'Department Verification'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created On'),
            'updated_at' => Yii::t('app', 'Updated On'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * {@inheritdoc}
     * @return IndustryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new IndustryQuery(get_called_class());
    }
}

user(unused)/controllers/IndustryController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Industry;
use app\models\IndustrySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * IndustryController implements the CRUD actions for Industry model.
 */
class IndustryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Industry models.
     * @return mixed
     */
    public function actionIndex()
    {
		$user_level = '';
		if(isset(Yii::$app->user->identity->user_level))
		$user_level = Yii::$app->user->identity->user_level;
	
        $searchModel = new IndustrySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		//if($user_level==1 || $user_level==2)
		//$dataProvider->query->andWhere(['dic_verified' => 1]);
	
		if($user_level==9)
		$dataProvider->query->andWhere(['district' => 'Dadra and Nagar Haveli']); 
		elseif($user_level==11)
		$dataProvider->query->andWhere(['district' => 'Daman']); 	
		elseif($user_level==13)
		$dataProvider->query->andWhere(['district' => 'Diu']); 	
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Industry model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Industry model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Industry();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Industry model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$old_verified = $model->verified;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			
			$post = Yii::$app->request->post('Industry');
			if($post['verified']=='1' && $post['verified']!=$old_verified)
			{
				$user = \app\models\User::findOne($model->user_id);
				$user->verified = '1';
				if($user->save(false))
				{
					$msg = "Dear ".$user->first_name." ".$user->last_name.". ";
					$msg .= "Thank you for registering OIDC Parivahan Suvidha. ";
					$msg .= "Username: ".$user->mobile_number." ";
					$msg .= "Password: ".$user->temp_password;
					$mobile = $user->mobile_number;
					$this->_sendTextSMS($mobile,$msg);
				}
			}
            return $this->redirect(['index', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Industry model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Industry model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Industry the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Industry::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
	protected function _sendTextSMS($mobile,$message) {	

		if(!WEB_SMS) return true;
		if($mobile != '' && $message != ''){
			$baseUri = 'https://alerts.solutionsinfini.com/api/v4';
	 		$params = array(
	 			'api_key' => WEB_SMS_API_KEY,
	            'message' => $message,
	            'to'      => $mobile,
	            'method'  => 'sms',
	            'sender'  => WEB_SMS_SENDER,
	            'format'  => 'php',
	            'unicode' => '0',
	        );
	 		$request_url = $baseUri.'/?'.http_build_query($params);
	        $request = curl_init($request_url);
	        curl_setopt($request,CURLOPT_RETURNTRANSFER,true );
	        curl_setopt($request,CURLOPT_SSL_VERIFYPEER,false);
	        $response = curl_exec($request);
			$res = unserialize($response);
	        return $res; 
		}
		else
			return false;
		
	}
}

user(unused)/views/industry/_form.php
<?php
use yii;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Industry */
/* @var $form yii\widgets\ActiveForm */
$full_path = SITE_PATH. 'uploads/industry/';    
$user_level = Yii::$app->user->identity->user_level;
?>

<div class="industry-form">

    <?php $form = ActiveForm::begin(); ?>
	
	<div class="col-xs-12 col-sm-12 col-md-12 col-xl-12">
	<div class="blue-title"><h4>&nbsp;</h4></div>
	<div class="table-responsive">
	 <table id="w-0" class="table table-striped table-bordered detail-view">
			<tbody>
			<!--<tr>
				<td><span>Incorporation Certificate Photo  : </span></td><td><a target="_blank" href="<?=$full_path.$model->incorporation_certificate_photo?>">click here</a></td>
				<td><span>Shop Establishment Certificate Photo  : </span></td><td><a target="_blank" href="<?=$full_path.$model->shop_establishment_certificate_photo?>">click here</a></td>
			</tr>-->
			<tr>
				<!--<td><span>Aadhar Photo  : </span></td><td><a target="_blank" href="<?=$full_path.$model->aadhaar_photo?>">click here</a></td>-->
				<!--<td><span>PAN Photo  : </span></td><td><a target="_blank" href="<?=$full_path.$model->pan_photo?>">click here</a></td>-->
				<td><b>Any of the Government registered certificate / GST Certificate / VAT Certificate / Labour Department Certificate / Electricity Bill Copy  : </b>&nbsp;&nbsp;&nbsp;<a target="_blank" href="<?=$full_path.$model->any_government_doc_photo?>">click here</a></td>
			</tr>
			<?php if(!empty($model->udhyog_aadhaar_certificate_photo)) { ?>
			<tr>
				<td><b>Udhyog Aadhaar Certificate Copy  : </b>&nbsp;&nbsp;&nbsp;<a target="_blank" href="<?=$full_path.$model->udhyog_aadhaar_certificate_photo?>">click here</a></td>
			</tr>
			<?Php } ?>
			</tbody>
	</table>
	</div>
	</div>
	

    <?php //echo $form->field($model, 'user_id')->textInput() ?>

	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'mobile_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'company_name')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'company_type')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'address_line1')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'address_line2')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'district')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'area')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'pincode')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'landmark')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>	
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'any_government_doc_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<?php if(!empty($model->udhyog_aadhaar_certificate_number)) { ?>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'udhyog_aadhaar_certificate_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>
	<?php } ?>
	<!--<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'incorporation_certificate_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'shop_establishment_certificate_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'pan_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   -->
	<!--<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'incorporation_certificate_photo')->textInput(['maxlength' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'shop_establishment_certificate_photo')->textInput(['maxlength' => true]) ?>
	</div>   -->
	<!--<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'gst_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'aadhaar_number')->textInput(['maxlength' => true, 'readonly' => true]) ?>
	</div>-->   
	<!--<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'aadhaar_photo')->textInput(['maxlength' => true]) ?>
	</div>   
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'pan_photo')->textInput(['maxlength' => true]) ?>
	</div>-->   
	<?php if($user_level == 1 || $user_level== 2) { ?>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'verified')->dropDownList([ '0' => 'Pending', '1' => 'Approved', '2' => 'Rejected'])->label('OIDC Approval') ?>   
	</div>
	<?php } else { ?>
	<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
	<?= $form->field($model, 'verified')->dropDownList([ '0' => 'Pending', '1' => 'Approved', '2' => 'Rejected'])->label('OIDC Approval') ?>   
    <?php //echo $form->field($model, 'dic_verified')->dropDownList([ '0' => 'Pending', '1' => 'Verified', '2' => 'Rejected'])->label('DIC Verification') ?>   
	</div>
	<?php } ?>
	<div class="col-xs-12 col-sm-12 col-md-12 col-xl-12">
    <?= $form->field($model, 'rejection_remark')->textarea(['rows' => 2]) ?>
	</div>
	<!--<div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
    <?= $form->field($model, 'status')->dropDownList([ 'Active' => 'Active', 'Inactive' => 'Inactive'], ['prompt' => '']) ?>
	</div>-->
    <div class="clearfix"></div>
    <div class="col-sm-6 col-md-6 col-xl-6" style="margin-top:20px;">
	<div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?= Html::a('Cancel', ['/industry/index'], ['class'=>'btn btn-primary']) ?>
    </div>
	</div>
    <?php ActiveForm::end(); ?>

</div>

user(unused)/views/industry/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\IndustrySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="industry-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'mobile_number') ?>

    <?php // echo $form->field($model, 'company_name') ?>

    <?php // echo $form->field($model, 'company_type_id') ?>

    <?php // echo $form->field($model, 'company_type') ?>

    <?php // echo $form->field($model, 'incorporation_certificate_number') ?>

    <?php // echo $form->field($model, 'shop_establishment_certificate_number') ?>

    <?php // echo $form->field($model, 'pan_number') ?>

    <?php // echo $form->field($model, 'incorporation_certificate_photo') ?>

    <?php // echo $form->field($model, 'shop_establishment_certificate_photo') ?>

    <?php // echo $form->field($model, 'gst_number') ?>

    <?php // echo $form->field($model, 'aadhaar_number') ?>

    <?php // echo $form->field($model, 'aadhaar_photo') ?>

    <?php // echo $form->field($model, 'pan_photo') ?>

    <?php // echo $form->field($model, 'address_line1') ?>

    <?php // echo $form->field($model, 'address_line2') ?>

    <?php // echo $form->field($model, 'pincode') ?>

    <?php // echo $form->field($model, 'country') ?>

    <?php // echo $form->field($model, 'state') ?>

    <?php // echo $form->field($model, 'district') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'area') ?>

    <?php // echo $form->field($model, 'landmark') ?>

    <?php // echo $form->field($model, 'remark') ?>

    <?php // echo $form->field($model, 'verified') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

user(unused)/views/industry/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Industry */

$this->title = Yii::t('app', 'Create Industry');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Industries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="industry-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

user(unused)/views/industry/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\IndustrySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Service Seeker (Industry, Trader and Private User)');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="industry-index">

<?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'user_id',
			'company_name',
            'first_name',
            'last_name',
            'email:email',
            'mobile_number',
            //'company_type_id',
            //'company_type',
            //'incorporation_certificate_number',
            //'shop_establishment_certificate_number',
            //'pan_number',
            //'incorporation_certificate_photo',
            //'shop_establishment_certificate_photo',
            //'gst_number',
            //'aadhaar_number',
            //'aadhaar_photo',
            //'pan_photo',
            //'address_line1',
            //'address_line2',
            //'pincode',
            //'country',
            //'state',
            'district',
            //'city',
            //'area',
            //'landmark',
            //'remark',
            //'status',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',
			[
				'label' => 'Registered At',
				'attribute' => 'created_at',
				'format' => ['date', 'php:d-m-Y'],
				'headerOptions' => ['style' => 'width:10%'],
				'filter' => false,
            ],
			/* [
				'label' => 'DIC Verification',
				'attribute' => 'verified',
				'value' => function($model){
                         if($model->dic_verified == '0'){
                            return 'Pending';
                         }
						 elseif($model->dic_verified == '1'){
                            return 'Verified';
                         }
						 elseif($model->dic_verified == '2'){
                            return 'Rejected';
                         }
               },
			   'contentOptions' => function ($model, $key, $index, $column) {
                return ['style' => 'width:10%; color:' 
                        .(($model->dic_verified=='0')? 'blue' :
                         (($model->dic_verified=='1')? 'green' :
                          'red'))];
                },
				'filter' => false
			],*/
			[
				//'label' => 'OIDC Approval',
				'label' => 'Approval',
				'attribute' => 'verified',
				'value' => function($model){
                         if($model->verified == '0'){
                            return 'Pending';
                         }
						 elseif($model->verified == '1'){
                            return 'Approved';
                         }
						 elseif($model->verified == '2'){
                            return 'Rejected';
                         }
               },
			   'contentOptions' => function ($model, $key, $index, $column) {
                return ['style' => 'width:10%; color:' 
                        .(($model->verified=='0')? 'blue' :
                         (($model->verified=='1')? 'green' :
                          'red'))];
                },
				'filter' => false
			],
            [
                'header' => 'Action',
                'headerOptions' => ['width' => '5%','class' => ' table-th'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
                /*'buttons' =>
                [
                    'update' => function($url, $model) {
                         $url = Yii::$app->urlManager->createUrl(['/transporter/update-transporter']).'&user_id=' . $model->id;
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('app', 'Edit'),
                                    'data-pjax' => '0',
                        ]);
                    },
                ],*/
                'visible' => TRUE
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

user(unused)/views/industry/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Industry */

$this->title = Yii::t('app', 'Update Industry: {name}', [
    'name' => $model->company_name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Industries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->first_name, 'url' => ['index', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="industry-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

user(unused)/views/industry/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Industry */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Industries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="industry-view">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'user_id',
            'first_name',
            'last_name',
            'email:email',
            'mobile_number',
            'company_name',
            'company_type_id',
            'company_type',
            'incorporation_certificate_number',
            'shop_establishment_certificate_number',
            'pan_number',
            'incorporation_certificate_photo',
            'shop_establishment_certificate_photo',
            'gst_number',
            'aadhaar_number',
            'aadhaar_photo',
            'pan_photo',
            'address_line1',
            'address_line2',
            'pincode',
            'country',
            'state',
            'district',
            'city',
            'area',
            'landmark',
            //'remark',
            'verified',
            'status',
            'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',
        ],
    ]) ?>

</div>